#!/usr/bin/env sh

# HYPER == SHIFT + CMD + ALT + OPTION

# resize windows
hyper - u : yabai -m window --resize bottom:0:20
hyper - i : yabai -m window --resize top:0:-20
hyper - y : yabai -m window --resize left:-20:0
hyper - o : yabai -m window --resize right:20:0

# go between spaces, left-right
hyper - j : yabai -m space --focus prev || yabai -m space --focus last
hyper - k : yabai -m space --focus next || yabai -m space --focus first

# move and follow windows between spaces, left-right
hyper - h : bash ~/.config/skhd/move-left-follow.sh
hyper - l : bash ~/.config/skhd/move-right-follow.sh

# rotate the window tree by 90 degrees
hyper - r : yabai -m space --rotate 90

# balance the window tree
hyper - e : yabai -m space --balance

# move between windows in the space
hyper - 0x1E : yabai -m window --focus next # ]
hyper - 0x21 : yabai -m window --focus prev # [

# fullscreen
hyper - f : yabai -m window --toggle zoom-fullscreen
hyper - g : yabai -m window --toggle native-fullscreen

# toggles
hyper - a : yabai -m window --toggle float
hyper - s : yabai -m window --toggle sticky

# restarts
hyper - n : yabai --restart-service
hyper - m : brew services restart sketchybar
hyper - 0x2C : skhd --restart-service

# focus on specific spaces
hyper - 1 : yabai -m space --focus 1
hyper - 2 : yabai -m space --focus 2
hyper - 3 : yabai -m space --focus 3
hyper - 4 : yabai -m space --focus 4
hyper - 5 : yabai -m space --focus 5
hyper - 6 : yabai -m space --focus 6
hyper - 7 : yabai -m space --focus 7
hyper - 8 : yabai -m space --focus 8
hyper - 9 : yabai -m space --focus 9
hyper - 0 : yabai -m space --focus 10
